name: Test Coverage

on:
  push:
    branches:
      - master

jobs:
  test_coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.14'
      - name: Test
        run: uv run pytest --cov=hattori --cov-report=xml tests
      - name: Coverage
        uses: codecov/codecov-action@v7.0.0
